# Generated by Django 2.2.2 on 2020-01-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=80)),
                ('lname', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=20)),
                ('bday', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=25)),
                ('sadd', models.CharField(max_length=70)),
                ('padd', models.CharField(max_length=80)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('lang', models.CharField(max_length=20)),
                ('cast', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('sboard', models.CharField(max_length=20)),
                ('spassyear', models.CharField(max_length=20)),
                ('sscmark', models.CharField(max_length=20)),
                ('sscmarkobt', models.CharField(max_length=20)),
                ('spercentage', models.CharField(max_length=20)),
                ('hboard', models.CharField(max_length=20)),
                ('hpassyear', models.CharField(max_length=20)),
                ('hscmark', models.CharField(max_length=20)),
                ('hscmarkobt', models.CharField(max_length=20)),
                ('hpercentage', models.CharField(max_length=20)),
                ('gboard', models.CharField(max_length=20)),
                ('gpassyear', models.CharField(max_length=20)),
                ('gmark', models.CharField(max_length=20)),
                ('gmarkobt', models.CharField(max_length=20)),
                ('gpercentage', models.CharField(max_length=20)),
                ('photo', models.FileField(max_length=20, upload_to='')),
                ('sscmarkimg', models.FileField(max_length=20, upload_to='')),
                ('hscmarkimg', models.FileField(max_length=20, upload_to='')),
                ('ortho', models.CharField(max_length=30)),
                ('previousapp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
    ]
