# Generated by Django 2.2.2 on 2020-01-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]
    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=80)),
                ('lname', models.CharField(max_length=80)),
                ('father', models.CharField(max_length=80)),
                ('mother', models.CharField(max_length=80)),
                ('bdate', models.CharField(max_length=80)),
                ('mobile', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sadd', models.CharField(max_length=80)),
                ('padd', models.CharField(max_length=80)),
                ('district', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('lang', models.CharField(max_length=80)),
                ('cast', models.CharField(max_length=80)),
                ('Category', models.CharField(max_length=80)),
                ('sboard', models.CharField(max_length=80)),
                ('spassyear', models.CharField(max_length=80)),
                ('sscmark', models.CharField(max_length=80)),
                ('sscmarkobt', models.CharField(max_length=80)),
                ('spercentage', models.CharField(max_length=80)),
                ('hboard', models.CharField(max_length=80)),
                ('hpassyear', models.CharField(max_length=80)),
                ('hscmark', models.CharField(max_length=80)),
                ('hscmarkobt', models.CharField(max_length=80)),
                ('hpercentage', models.CharField(max_length=80)),
                ('gboard', models.CharField(max_length=80)),
                ('gpassyear', models.CharField(max_length=80)),
                ('gmark', models.CharField(max_length=80)),
                ('gmarkobt', models.CharField(max_length=80)),
                ('gpercentage', models.CharField(max_length=80)),
                ('ortho', models.CharField(max_length=80)),
                ('previousapp', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='applicants',
        ),
    ]
